name: Build artifact

on: push

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6

      - name: Build application
        shell: bash
        run: |
          hash=$(git log -n 1 --pretty=%h)
          release_name="YohanumaKoPatcher-$hash"
          echo "release_name=$release_name" >> $GITHUB_ENV

          curl -L "https://docs.google.com/feeds/download/spreadsheets/Export?key=$SHEETS_KEY&exportFormat=csv&gid=$GLOSSARY_GID" > KoPatchAssets/tables/glossary.csv
          curl -L "https://docs.google.com/feeds/download/spreadsheets/Export?key=$SHEETS_KEY&exportFormat=csv&gid=$GLOSSARY_DEMO_GID" > KoPatchAssets/tables/glossary_demo.csv
          curl -L "https://docs.google.com/feeds/download/spreadsheets/Export?key=$SHEETS_KEY&exportFormat=csv&gid=$TUTORIALPAGE_GID" > KoPatchAssets/tables/tutorialpage.csv
          curl -L "https://docs.google.com/feeds/download/spreadsheets/Export?key=$SHEETS_KEY&exportFormat=csv&gid=$STORY_GID" > KoPatchAssets/tables/story.csv
          curl -L "https://docs.google.com/feeds/download/spreadsheets/Export?key=$SHEETS_KEY&exportFormat=csv&gid=$UI_GID" > KoPatchAssets/tables/ui.csv 

          dotnet publish YohanumaKoPatcher/YohanumaKoPatcher.csproj -c Release -r win-x64 -p:PublishSingleFile=true --self-contained false -o "$release_name"
        env:
          SHEETS_KEY: ${{ vars.SHEETS_KEY }}
          GLOSSARY_GID: ${{ vars.GLOSSARY_GID }}
          GLOSSARY_DEMO_GID: ${{ vars.GLOSSARY_DEMO_GID }}
          TUTORIALPAGE_GID: ${{ vars.TUTORIALPAGE_GID }}
          STORY_GID: ${{ vars.STORY_GID }}
          UI_GID: ${{ vars.UI_GID }}
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.release_name }}
          path: |
            ${{ env.release_name }}/YohanumaKoPatcher.exe
            ${{ env.release_name }}/ko-patch-assets
