name: Build artifact

on: push

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6

      - name: Build application
        shell: bash
        run: |
          hash=$(git log -n 1 --pretty=%h)
          release_name="YohanumaKoPatcher-$hash"
          echo "release_name=$release_name" >> $GITHUB_ENV

          dotnet publish YohanumaKoPatcher/YohanumaKoPatcher.csproj -c Release -r win-x64 -p:PublishSingleFile=true --self-contained false -o "$release_name"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.release_name }}
          path: |
            ${{ env.release_name }}/YohanumaKoPatcher.exe
            ${{ env.release_name }}/ko-patch-assets
